import infrastructure as infra

import desugarers/absorb_next_sibling_while
import desugarers/add_attributes
import desugarers/add_attribute_to_second_of_kind
import desugarers/add_before_tags_but_not_before_first_of_kind
import desugarers/add_before_tags_but_not_first_child_tags
import desugarers/add_between_tag_and_text_node
import desugarers/add_between_tags
import desugarers/add_attribute_when_child_of
import desugarers/associate_counter_by_prepending_incrementing_attribute
import desugarers/auto_generate_child_if_missing_from_attribute
import desugarers/auto_generate_child_if_missing_from_first_descendant_of_type
import desugarers/break_lines_into_span_tooltips
import desugarers/change_attribute_value
import desugarers/concatenate_text_nodes
import desugarers/convert_int_attributes_to_float
import desugarers/counters_substitute_and_assign_handles
import desugarers/cut_paste_attribute_from_first_child_to_self
import desugarers/cut_paste_attribute_from_self_to_child
import desugarers/extract_starting_and_ending_spaces
import desugarers/find_replace
import desugarers/fold_tag_contents_into_text
import desugarers/fold_tags_into_text
import desugarers/free_children
import desugarers/generate_lbp_breadcrumbs
import desugarers/generate_lbp_prev_next_attributes
import desugarers/generate_lbp_table_of_contents
import desugarers/generate_ti2_table_of_contents_html
import desugarers/generate_ti3_index_element
import desugarers/group_consecutive_children_avoiding
import desugarers/handles_generate_dictionary
import desugarers/handles_generate_ids
import desugarers/handles_substitute
import desugarers/identity
import desugarers/insert_bookend_tags
import desugarers/insert_bookend_text_if_no_attributes
import desugarers/normalize_math_delimiters_inside
import desugarers/pair_bookends
import desugarers/prepend_text
import desugarers/prepend_text_if_has_ancestor_else
import desugarers/reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node
import desugarers/rearrange_links
import desugarers/remove_attributes
import desugarers/remove_empty_chunks
import desugarers/remove_empty_lines
import desugarers/remove_starting_and_ending_empty_lines
import desugarers/remove_starting_and_ending_spaces
import desugarers/remove_text_nodes_with_singleton_empty_line
import desugarers/rename
import desugarers/rename_attributes
import desugarers/rename_when_child_of
import desugarers/rename_with_attributes
import desugarers/unwrap
import desugarers/unwrap_tags_if_no_attributes
import desugarers/unwrap_vertical_chunks_with_no_text_child
import desugarers/unwrap_when_child_of
import desugarers/unwrap_when_descendant_of
import desugarers/unwrap_when_zero_or_one_children
import desugarers/wrap_math_with_no_break
import desugarers/wrap_children_before_in

pub const all_test_groups : List(fn() -> infra.AssertiveTestGroup(List(#(String, String)))) = [
  absorb_next_sibling_while.test_group,
]