import desugarers/absorb_next_sibling_while
import desugarers/add_before_tags_but_not_first_child_tags
import desugarers/add_between_tag_and_text_node
import desugarers/add_between_tags
import desugarers/add_counter_attributes
import desugarers/add_title_counters_and_titles_with_handle_assignments
import desugarers/add_attribute_to_if_child_of_but_no_overwrites
import desugarers/change_attribute_value
import desugarers/concatenate_text_nodes
import desugarers/convert_int_attributes_to_float
import desugarers/counters_substitute_and_assign_handles
import desugarers/define_article_output_path
import desugarers/find_replace
import desugarers/fold_tag_contents_into_text
import desugarers/fold_tags_into_text
import desugarers/free_children
import desugarers/generate_handles_attributes
import desugarers/handles_generate_ids
import desugarers/generate_lbp_links
import desugarers/generate_lbp_table_of_contents
import desugarers/group_consecutive_children_avoiding
import desugarers/handles_generate_dictionary
import desugarers/handles_substitute
import desugarers/identity
import desugarers/insert_bookend_tags
import desugarers/insert_indent
import desugarers/pair_bookends
import desugarers/remove_attributes
import desugarers/remove_empty_chunks
import desugarers/remove_empty_text_nodes
import desugarers/remove_starting_and_ending_empty_lines
import desugarers/remove_starting_and_ending_spaces
import desugarers/remove_vertical_chunks_with_no_text_child
import desugarers/rename_tag
import desugarers/rename_when_child_of
import desugarers/unwrap_tags
import desugarers/unwrap_tags_if_descendants_of
import desugarers/unwrap_tags_if_single_child
import desugarers/wrap_math_with_no_break

pub const absorb_next_sibling_while = absorb_next_sibling_while.absorb_next_sibling_while
pub const add_before_tags_but_not_first_child_tags = add_before_tags_but_not_first_child_tags.add_before_tags_but_not_first_child_tags
pub const add_between_tag_and_text_node = add_between_tag_and_text_node.add_between_tag_and_text_node
pub const add_between_tags = add_between_tags.add_between_tags
pub const add_counter_attributes = add_counter_attributes.add_counter_attributes
pub const add_title_counters_and_titles_with_handle_assignments = add_title_counters_and_titles_with_handle_assignments.add_title_counters_and_titles_with_handle_assignments
pub const add_attribute_to_if_child_of_but_no_overwrites = add_attribute_to_if_child_of_but_no_overwrites.add_attribute_to_if_child_of_but_no_overwrites
pub const change_attribute_value = change_attribute_value.change_attribute_value
pub const concatenate_text_nodes = concatenate_text_nodes.concatenate_text_nodes
pub const convert_int_attributes_to_float = convert_int_attributes_to_float.convert_int_attributes_to_float
pub const counters_substitute_and_assign_handles = counters_substitute_and_assign_handles.counters_substitute_and_assign_handles
pub const define_article_output_path = define_article_output_path.define_article_output_path
pub const fold_tag_contents_into_text = fold_tag_contents_into_text.fold_tag_contents_into_text
pub const fold_tags_into_text = fold_tags_into_text.fold_tags_into_text
pub const find_replace = find_replace.find_replace
pub const free_children = free_children.free_children
pub const generate_handles_attributes = generate_handles_attributes.generate_handles_attributes
pub const handles_generate_ids = handles_generate_ids.handles_generate_ids
pub const generate_lbp_links = generate_lbp_links.generate_lbp_links
pub const generate_lbp_table_of_contents = generate_lbp_table_of_contents.generate_lbp_table_of_contents
pub const group_consecutive_children_avoiding = group_consecutive_children_avoiding.group_consecutive_children_avoiding
pub const handles_generate_dictionary = handles_generate_dictionary.handles_generate_dictionary
pub const handles_substitute = handles_substitute.handles_substitute
pub const identity = identity.identity
pub const insert_bookend_tags = insert_bookend_tags.insert_bookend_tags
pub const insert_indent = insert_indent.insert_indent
pub const pair_bookends = pair_bookends.pair_bookends
pub const remove_attributes = remove_attributes.remove_attributes
pub const remove_empty_chunks = remove_empty_chunks.remove_empty_chunks
pub const remove_empty_text_nodes = remove_empty_text_nodes.remove_empty_text_nodes
pub const remove_starting_and_ending_empty_lines = remove_starting_and_ending_empty_lines.remove_starting_and_ending_empty_lines
pub const remove_starting_and_ending_spaces = remove_starting_and_ending_spaces.remove_starting_and_ending_spaces
pub const remove_vertical_chunks_with_no_text_child = remove_vertical_chunks_with_no_text_child.remove_vertical_chunks_with_no_text_child
pub const rename_tag = rename_tag.rename_tag
pub const rename_when_child_of = rename_when_child_of.rename_when_child_of
pub const unwrap_tags = unwrap_tags.unwrap_tags
pub const unwrap_tags_if_descendants_of = unwrap_tags_if_descendants_of.unwrap_tags_if_descendants_of
pub const unwrap_tags_if_single_child = unwrap_tags_if_single_child.unwrap_tags_if_single_child
pub const wrap_math_with_no_break = wrap_math_with_no_break.wrap_math_with_no_break
