import desugarers/absorb_next_sibling_while
import desugarers/add_attributes
import desugarers/add_attribute_to_second_of_kind
import desugarers/add_before_tags_but_not_first_child_tags
import desugarers/add_between_tag_and_text_node
import desugarers/add_between_tags
import desugarers/add_attribute_when_child_of
import desugarers/associate_counter_by_prepending_incrementing_attribute
import desugarers/auto_generate_child_if_missing_from_attribute
import desugarers/auto_generate_child_if_missing_from_first_descendant_of_type
import desugarers/break_lines_into_span_tooltips
import desugarers/change_attribute_value
import desugarers/concatenate_text_nodes
import desugarers/convert_int_attributes_to_float
import desugarers/counters_substitute_and_assign_handles
import desugarers/cut_paste_attribute_from_first_child_to_self
import desugarers/cut_paste_attribute_from_self_to_child
import desugarers/extract_starting_and_ending_spaces
import desugarers/find_replace
import desugarers/fold_tag_contents_into_text
import desugarers/fold_tags_into_text
import desugarers/free_children
import desugarers/generate_lbp_prev_next_a_tags
import desugarers/generate_lbp_prev_next_attributes
import desugarers/generate_lbp_section_breadcrumbs
import desugarers/generate_lbp_table_of_contents
import desugarers/generate_ti2_table_of_contents_html
import desugarers/group_consecutive_children_avoiding
import desugarers/handles_generate_dictionary
import desugarers/handles_generate_ids
import desugarers/handles_substitute
import desugarers/identity
import desugarers/insert_bookend_tags
import desugarers/insert_bookend_text_if_no_attributes
import desugarers/normalize_math_delimiters_inside
import desugarers/pair_bookends
import desugarers/prepend_text
import desugarers/prepend_text_if_has_ancestor_else
import desugarers/reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node
import desugarers/rearrange_links
import desugarers/remove_attributes
import desugarers/remove_empty_chunks
import desugarers/remove_empty_lines
import desugarers/remove_starting_and_ending_empty_lines
import desugarers/remove_starting_and_ending_spaces
import desugarers/remove_text_nodes_with_singleton_empty_line
import desugarers/rename
import desugarers/rename_attributes
import desugarers/rename_when_child_of
import desugarers/rename_with_attributes
import desugarers/unwrap
import desugarers/unwrap_tags_if_no_attributes
import desugarers/unwrap_vertical_chunks_with_no_text_child
import desugarers/unwrap_when_child_of
import desugarers/unwrap_when_descendant_of
import desugarers/unwrap_when_zero_or_one_children
import desugarers/wrap_math_with_no_break
import desugarers/wrap_children_before_in

pub const absorb_next_sibling_while = absorb_next_sibling_while.absorb_next_sibling_while
pub const add_attributes = add_attributes.add_attributes
pub const auto_generate_child_if_missing_from_first_descendant_of_type = auto_generate_child_if_missing_from_first_descendant_of_type.auto_generate_child_if_missing_from_first_descendant_of_type
pub const auto_generate_child_if_missing_from_attribute = auto_generate_child_if_missing_from_attribute.auto_generate_child_if_missing_from_attribute
pub const add_attribute_to_second_of_kind = add_attribute_to_second_of_kind.add_attribute_to_second_of_kind
pub const add_before_tags_but_not_first_child_tags = add_before_tags_but_not_first_child_tags.add_before_tags_but_not_first_child_tags
pub const add_between_tag_and_text_node = add_between_tag_and_text_node.add_between_tag_and_text_node
pub const add_between_tags = add_between_tags.add_between_tags
pub const add_attribute_when_child_of = add_attribute_when_child_of.add_attribute_when_child_of
pub const associate_counter_by_prepending_incrementing_attribute = associate_counter_by_prepending_incrementing_attribute.associate_counter_by_prepending_incrementing_attribute
pub const break_lines_into_span_tooltips = break_lines_into_span_tooltips.break_lines_into_span_tooltips
pub const change_attribute_value = change_attribute_value.change_attribute_value
pub const concatenate_text_nodes = concatenate_text_nodes.concatenate_text_nodes
pub const convert_int_attributes_to_float = convert_int_attributes_to_float.convert_int_attributes_to_float
pub const counters_substitute_and_assign_handles = counters_substitute_and_assign_handles.counters_substitute_and_assign_handles
pub const cut_paste_attribute_from_first_child_to_self = cut_paste_attribute_from_first_child_to_self.cut_paste_attribute_from_first_child_to_self
pub const cut_paste_attribute_from_self_to_child = cut_paste_attribute_from_self_to_child.cut_paste_attribute_from_self_to_child
pub const extract_starting_and_ending_spaces = extract_starting_and_ending_spaces.extract_starting_and_ending_spaces
pub const fold_tag_contents_into_text = fold_tag_contents_into_text.fold_tag_contents_into_text
pub const fold_tags_into_text = fold_tags_into_text.fold_tags_into_text
pub const find_replace = find_replace.find_replace
pub const free_children = free_children.free_children
pub const generate_lbp_prev_next_a_tags = generate_lbp_prev_next_a_tags.generate_lbp_prev_next_a_tags
pub const generate_lbp_prev_next_attributes = generate_lbp_prev_next_attributes.generate_lbp_prev_next_attributes
pub const generate_lbp_section_breadcrumbs = generate_lbp_section_breadcrumbs.generate_lbp_section_breadcrumbs
pub const generate_lbp_table_of_contents = generate_lbp_table_of_contents.generate_lbp_table_of_contents
pub const generate_ti2_table_of_contents_html = generate_ti2_table_of_contents_html.generate_ti2_table_of_contents_html
pub const group_consecutive_children_avoiding = group_consecutive_children_avoiding.group_consecutive_children_avoiding
pub const handles_generate_dictionary = handles_generate_dictionary.handles_generate_dictionary
pub const handles_generate_ids = handles_generate_ids.handles_generate_ids
pub const handles_substitute = handles_substitute.handles_substitute
pub const identity = identity.identity
pub const insert_bookend_tags = insert_bookend_tags.insert_bookend_tags
pub const insert_bookend_text_if_no_attributes = insert_bookend_text_if_no_attributes.insert_bookend_text_if_no_attributes
pub const normalize_math_delimiters_inside = normalize_math_delimiters_inside.normalize_math_delimiters_inside
pub const pair_bookends = pair_bookends.pair_bookends
pub const prepend_text = prepend_text.prepend_text
pub const prepend_text_if_has_ancestor_else = prepend_text_if_has_ancestor_else.prepend_text_if_has_ancestor_else
pub const rearrange_links = rearrange_links.rearrange_links
pub const reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node = reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node.reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node
pub const remove_attributes = remove_attributes.remove_attributes
pub const remove_empty_chunks = remove_empty_chunks.remove_empty_chunks
pub const remove_empty_lines = remove_empty_lines.remove_empty_lines
pub const remove_starting_and_ending_empty_lines = remove_starting_and_ending_empty_lines.remove_starting_and_ending_empty_lines
pub const remove_starting_and_ending_spaces = remove_starting_and_ending_spaces.remove_starting_and_ending_spaces
pub const remove_text_nodes_with_singleton_empty_line = remove_text_nodes_with_singleton_empty_line.remove_text_nodes_with_singleton_empty_line
pub const rename = rename.rename
pub const rename_attributes = rename_attributes.rename_attributes
pub const rename_when_child_of = rename_when_child_of.rename_when_child_of
pub const rename_with_attributes = rename_with_attributes.rename_with_attributes
pub const unwrap = unwrap.unwrap
pub const unwrap_tags_if_no_attributes = unwrap_tags_if_no_attributes.unwrap_tags_if_no_attributes
pub const unwrap_vertical_chunks_with_no_text_child = unwrap_vertical_chunks_with_no_text_child.unwrap_vertical_chunks_with_no_text_child
pub const unwrap_when_child_of= unwrap_when_child_of.unwrap_when_child_of
pub const unwrap_when_descendant_of = unwrap_when_descendant_of.unwrap_when_descendant_of
pub const unwrap_when_zero_or_one_children = unwrap_when_zero_or_one_children.unwrap_when_zero_or_one_children
pub const wrap_children_before_in = wrap_children_before_in.wrap_children_before_in
pub const wrap_math_with_no_break = wrap_math_with_no_break.wrap_math_with_no_break
