import infrastructure as infra
import desugarers/absorb_next_sibling_while
import desugarers/add_after_tags_but_not_last_child_tags
import desugarers/add_attribute_to_second_of_kind
import desugarers/add_attribute_when_child_of
import desugarers/add_attributes
import desugarers/add_before_tags_but_not_before_first_of_kind
import desugarers/add_before_tags_but_not_first_child_tags
import desugarers/add_between_tag_and_text_node
import desugarers/add_between_tags
import desugarers/add_spacer_divs_after
import desugarers/add_spacer_divs_before
import desugarers/add_spacer_divs_between
import desugarers/append_class_to_child_if
import desugarers/append_class_to_children_with_class
import desugarers/append_class_to_children_with_tag
import desugarers/associate_counter_by_prepending_incrementing_attribute
import desugarers/auto_generate_child_if_missing_from_attribute
import desugarers/auto_generate_child_if_missing_from_first_descendant_of_type
import desugarers/break_lines_into_span_tooltips
import desugarers/change_attribute_value
import desugarers/concatenate_tags
import desugarers/concatenate_text_nodes
import desugarers/convert_int_attributes_to_float
import desugarers/correct_parsed_html_tags
import desugarers/counters_substitute_and_assign_handles
import desugarers/cut_paste_attribute_from_first_child_to_self
import desugarers/cut_paste_attribute_from_self_to_child
import desugarers/encode_spaces_in_first_and_last_child
import desugarers/extract_starting_and_ending_spaces
import desugarers/filter_nodes_by_attributes
import desugarers/find_replace
import desugarers/find_replace_in_descendants_of
import desugarers/fix_ti2_local_links
import desugarers/fold_tag_contents_into_text
import desugarers/fold_tags_into_text
import desugarers/free_children
import desugarers/generate_lbp_breadcrumbs
import desugarers/generate_lbp_prev_next_attributes
import desugarers/generate_lbp_sections_breadcrumbs
import desugarers/generate_lbp_table_of_contents
import desugarers/generate_ti2_table_of_contents
import desugarers/generate_ti2_table_of_contents_html
import desugarers/generate_ti3_index_element
import desugarers/generate_ti3_menu
import desugarers/group_consecutive_children_avoiding
import desugarers/handles_generate_dictionary
import desugarers/handles_generate_ids
import desugarers/handles_substitute
import desugarers/identity
import desugarers/insert_bookend_tags
import desugarers/insert_bookend_text
import desugarers/insert_bookend_text_if_no_attributes
import desugarers/insert_ti2_counter_commands
import desugarers/keep_only_subtrees_and_ancestors_of_nodes_matching_a_key_value_pair
import desugarers/merge_parent_attributes_into_child
import desugarers/normalize_math_delimiters_inside
import desugarers/pair_bookends
import desugarers/pair_double_dollars_together
import desugarers/prepend_append_to_text_children_of
import desugarers/prepend_text
import desugarers/prepend_text_if_has_ancestor_else
import desugarers/rearrange_links
import desugarers/reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node
import desugarers/reinsert_math_dollar
import desugarers/remove_attributes
import desugarers/remove_attributes_for_parents
import desugarers/remove_chapter_number_from_title
import desugarers/remove_empty_lines
import desugarers/remove_empty_tags
import desugarers/remove_outside_subtrees
import desugarers/remove_starting_and_ending_empty_lines
import desugarers/remove_starting_and_ending_spaces
import desugarers/remove_tag
import desugarers/remove_text_nodes_with_singleton_empty_line
import desugarers/rename
import desugarers/rename_attributes
import desugarers/rename_attributes_by_function
import desugarers/rename_when_child_of
import desugarers/rename_with_attributes
import desugarers/replace_in_attribute_values
import desugarers/replace_multiple_spaces_by_one
import desugarers/replace_text_parent_by_text_bookends
import desugarers/split_by_indexed_regexes
import desugarers/split_content_by_low_level_delimiters
import desugarers/split_with_replacement_instructions
import desugarers/surround_elements_by
import desugarers/ti2_carousel_component
import desugarers/trim_spaces_around_newlines
import desugarers/unwrap
import desugarers/unwrap_tag_when_child_of_tag
import desugarers/unwrap_tag_when_parent_of_tag
import desugarers/unwrap_tags_if_attributes_match
import desugarers/unwrap_tags_if_no_attributes
import desugarers/unwrap_tags_when_no_child_meets_condition
import desugarers/unwrap_tags_with_no_text_child
import desugarers/unwrap_tags_with_no_text_descendant
import desugarers/unwrap_when_child_of
import desugarers/unwrap_when_descendant_of
import desugarers/unwrap_when_zero_or_one_children
import desugarers/wrap_adjacent_non_whitespace_text_with
import desugarers/wrap_children_before_in
import desugarers/wrap_element_children

pub const absorb_next_sibling_while = absorb_next_sibling_while.absorb_next_sibling_while
pub const add_after_tags_but_not_last_child_tags = add_after_tags_but_not_last_child_tags.add_after_tags_but_not_last_child_tags
pub const add_attribute_to_second_of_kind = add_attribute_to_second_of_kind.add_attribute_to_second_of_kind
pub const add_attribute_when_child_of = add_attribute_when_child_of.add_attribute_when_child_of
pub const add_attributes = add_attributes.add_attributes
pub const add_before_tags_but_not_before_first_of_kind = add_before_tags_but_not_before_first_of_kind.add_before_tags_but_not_before_first_of_kind
pub const add_before_tags_but_not_first_child_tags = add_before_tags_but_not_first_child_tags.add_before_tags_but_not_first_child_tags
pub const add_between_tag_and_text_node = add_between_tag_and_text_node.add_between_tag_and_text_node
pub const add_between_tags = add_between_tags.add_between_tags
pub const add_spacer_divs_after = add_spacer_divs_after.add_spacer_divs_after
pub const add_spacer_divs_before = add_spacer_divs_before.add_spacer_divs_before
pub const add_spacer_divs_between = add_spacer_divs_between.add_spacer_divs_between
pub const append_class_to_child_if = append_class_to_child_if.append_class_to_child_if
pub const append_class_to_children_with_class = append_class_to_children_with_class.append_class_to_children_with_class
pub const append_class_to_children_with_tag = append_class_to_children_with_tag.append_class_to_children_with_tag
pub const associate_counter_by_prepending_incrementing_attribute = associate_counter_by_prepending_incrementing_attribute.associate_counter_by_prepending_incrementing_attribute
pub const auto_generate_child_if_missing_from_attribute = auto_generate_child_if_missing_from_attribute.auto_generate_child_if_missing_from_attribute
pub const auto_generate_child_if_missing_from_first_descendant_of_type = auto_generate_child_if_missing_from_first_descendant_of_type.auto_generate_child_if_missing_from_first_descendant_of_type
pub const break_lines_into_span_tooltips = break_lines_into_span_tooltips.break_lines_into_span_tooltips
pub const change_attribute_value = change_attribute_value.change_attribute_value
pub const concatenate_tags = concatenate_tags.concatenate_tags
pub const concatenate_text_nodes = concatenate_text_nodes.concatenate_text_nodes
pub const convert_int_attributes_to_float = convert_int_attributes_to_float.convert_int_attributes_to_float
pub const correct_parsed_html_tags = correct_parsed_html_tags.correct_parsed_html_tags
pub const counters_substitute_and_assign_handles = counters_substitute_and_assign_handles.counters_substitute_and_assign_handles
pub const cut_paste_attribute_from_first_child_to_self = cut_paste_attribute_from_first_child_to_self.cut_paste_attribute_from_first_child_to_self
pub const cut_paste_attribute_from_self_to_child = cut_paste_attribute_from_self_to_child.cut_paste_attribute_from_self_to_child
pub const encode_spaces_in_first_and_last_child = encode_spaces_in_first_and_last_child.encode_spaces_in_first_and_last_child
pub const extract_starting_and_ending_spaces = extract_starting_and_ending_spaces.extract_starting_and_ending_spaces
pub const filter_nodes_by_attributes = filter_nodes_by_attributes.filter_nodes_by_attributes
pub const find_replace = find_replace.find_replace
pub const find_replace_in_descendants_of = find_replace_in_descendants_of.find_replace_in_descendants_of
pub const fix_ti2_local_links = fix_ti2_local_links.fix_ti2_local_links
pub const fold_tag_contents_into_text = fold_tag_contents_into_text.fold_tag_contents_into_text
pub const fold_tags_into_text = fold_tags_into_text.fold_tags_into_text
pub const free_children = free_children.free_children
pub const generate_lbp_breadcrumbs = generate_lbp_breadcrumbs.generate_lbp_breadcrumbs
pub const generate_lbp_prev_next_attributes = generate_lbp_prev_next_attributes.generate_lbp_prev_next_attributes
pub const generate_lbp_sections_breadcrumbs = generate_lbp_sections_breadcrumbs.generate_lbp_sections_breadcrumbs
pub const generate_lbp_table_of_contents = generate_lbp_table_of_contents.generate_lbp_table_of_contents
pub const generate_ti2_table_of_contents = generate_ti2_table_of_contents.generate_ti2_table_of_contents
pub const generate_ti2_table_of_contents_html = generate_ti2_table_of_contents_html.generate_ti2_table_of_contents_html
pub const generate_ti3_index_element = generate_ti3_index_element.generate_ti3_index_element
pub const generate_ti3_menu = generate_ti3_menu.generate_ti3_menu
pub const group_consecutive_children_avoiding = group_consecutive_children_avoiding.group_consecutive_children_avoiding
pub const handles_generate_dictionary = handles_generate_dictionary.handles_generate_dictionary
pub const handles_generate_ids = handles_generate_ids.handles_generate_ids
pub const handles_substitute = handles_substitute.handles_substitute
pub const identity = identity.identity
pub const insert_bookend_tags = insert_bookend_tags.insert_bookend_tags
pub const insert_bookend_text = insert_bookend_text.insert_bookend_text
pub const insert_bookend_text_if_no_attributes = insert_bookend_text_if_no_attributes.insert_bookend_text_if_no_attributes
pub const insert_ti2_counter_commands = insert_ti2_counter_commands.insert_ti2_counter_commands
pub const keep_only_subtrees_and_ancestors_of_nodes_matching_a_key_value_pair = keep_only_subtrees_and_ancestors_of_nodes_matching_a_key_value_pair.keep_only_subtrees_and_ancestors_of_nodes_matching_a_key_value_pair
pub const merge_parent_attributes_into_child = merge_parent_attributes_into_child.merge_parent_attributes_into_child
pub const normalize_math_delimiters_inside = normalize_math_delimiters_inside.normalize_math_delimiters_inside
pub const pair_bookends = pair_bookends.pair_bookends
pub const pair_double_dollars_together = pair_double_dollars_together.pair_double_dollars_together
pub const prepend_append_to_text_children_of = prepend_append_to_text_children_of.prepend_append_to_text_children_of
pub const prepend_text = prepend_text.prepend_text
pub const prepend_text_if_has_ancestor_else = prepend_text_if_has_ancestor_else.prepend_text_if_has_ancestor_else
pub const rearrange_links = rearrange_links.rearrange_links
pub const reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node = reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node.reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node
pub const reinsert_math_dollar = reinsert_math_dollar.reinsert_math_dollar
pub const remove_attributes = remove_attributes.remove_attributes
pub const remove_attributes_for_parents = remove_attributes_for_parents.remove_attributes_for_parents
pub const remove_chapter_number_from_title = remove_chapter_number_from_title.remove_chapter_number_from_title
pub const remove_empty_lines = remove_empty_lines.remove_empty_lines
pub const remove_empty_tags = remove_empty_tags.remove_empty_tags
pub const remove_outside_subtrees = remove_outside_subtrees.remove_outside_subtrees
pub const remove_starting_and_ending_empty_lines = remove_starting_and_ending_empty_lines.remove_starting_and_ending_empty_lines
pub const remove_starting_and_ending_spaces = remove_starting_and_ending_spaces.remove_starting_and_ending_spaces
pub const remove_tag = remove_tag.remove_tag
pub const remove_text_nodes_with_singleton_empty_line = remove_text_nodes_with_singleton_empty_line.remove_text_nodes_with_singleton_empty_line
pub const rename = rename.rename
pub const rename_attributes = rename_attributes.rename_attributes
pub const rename_attributes_by_function = rename_attributes_by_function.rename_attributes_by_function
pub const rename_when_child_of = rename_when_child_of.rename_when_child_of
pub const rename_with_attributes = rename_with_attributes.rename_with_attributes
pub const replace_in_attribute_values = replace_in_attribute_values.replace_in_attribute_values
pub const replace_multiple_spaces_by_one = replace_multiple_spaces_by_one.replace_multiple_spaces_by_one
pub const replace_text_parent_by_text_bookends = replace_text_parent_by_text_bookends.replace_text_parent_by_text_bookends
pub const split_by_indexed_regexes = split_by_indexed_regexes.split_by_indexed_regexes
pub const split_content_by_low_level_delimiters = split_content_by_low_level_delimiters.split_content_by_low_level_delimiters
pub const split_with_replacement_instructions = split_with_replacement_instructions.split_with_replacement_instructions
pub const surround_elements_by = surround_elements_by.surround_elements_by
pub const ti2_carousel_component = ti2_carousel_component.ti2_carousel_component
pub const trim_spaces_around_newlines = trim_spaces_around_newlines.trim_spaces_around_newlines
pub const unwrap = unwrap.unwrap
pub const unwrap_tag_when_child_of_tag = unwrap_tag_when_child_of_tag.unwrap_tag_when_child_of_tag
pub const unwrap_tag_when_parent_of_tag = unwrap_tag_when_parent_of_tag.unwrap_tag_when_parent_of_tag
pub const unwrap_tags_if_attributes_match = unwrap_tags_if_attributes_match.unwrap_tags_if_attributes_match
pub const unwrap_tags_if_no_attributes = unwrap_tags_if_no_attributes.unwrap_tags_if_no_attributes
pub const unwrap_tags_when_no_child_meets_condition = unwrap_tags_when_no_child_meets_condition.unwrap_tags_when_no_child_meets_condition
pub const unwrap_tags_with_no_text_child = unwrap_tags_with_no_text_child.unwrap_tags_with_no_text_child
pub const unwrap_tags_with_no_text_descendant = unwrap_tags_with_no_text_descendant.unwrap_tags_with_no_text_descendant
pub const unwrap_when_child_of = unwrap_when_child_of.unwrap_when_child_of
pub const unwrap_when_descendant_of = unwrap_when_descendant_of.unwrap_when_descendant_of
pub const unwrap_when_zero_or_one_children = unwrap_when_zero_or_one_children.unwrap_when_zero_or_one_children
pub const wrap_adjacent_non_whitespace_text_with = wrap_adjacent_non_whitespace_text_with.wrap_adjacent_non_whitespace_text_with
pub const wrap_children_before_in = wrap_children_before_in.wrap_children_before_in
pub const wrap_element_children = wrap_element_children.wrap_element_children

pub const assertive_tests : List(fn() -> infra.AssertiveTests) = [
  absorb_next_sibling_while.assertive_tests,
  add_after_tags_but_not_last_child_tags.assertive_tests,
  add_attribute_to_second_of_kind.assertive_tests,
  add_attribute_when_child_of.assertive_tests,
  add_attributes.assertive_tests,
  add_before_tags_but_not_before_first_of_kind.assertive_tests,
  add_before_tags_but_not_first_child_tags.assertive_tests,
  add_between_tag_and_text_node.assertive_tests,
  add_between_tags.assertive_tests,
  add_spacer_divs_after.assertive_tests,
  add_spacer_divs_before.assertive_tests,
  add_spacer_divs_between.assertive_tests,
  append_class_to_child_if.assertive_tests,
  append_class_to_children_with_class.assertive_tests,
  append_class_to_children_with_tag.assertive_tests,
  associate_counter_by_prepending_incrementing_attribute.assertive_tests,
  auto_generate_child_if_missing_from_attribute.assertive_tests,
  auto_generate_child_if_missing_from_first_descendant_of_type.assertive_tests,
  break_lines_into_span_tooltips.assertive_tests,
  change_attribute_value.assertive_tests,
  concatenate_tags.assertive_tests,
  concatenate_text_nodes.assertive_tests,
  convert_int_attributes_to_float.assertive_tests,
  correct_parsed_html_tags.assertive_tests,
  counters_substitute_and_assign_handles.assertive_tests,
  cut_paste_attribute_from_first_child_to_self.assertive_tests,
  cut_paste_attribute_from_self_to_child.assertive_tests,
  encode_spaces_in_first_and_last_child.assertive_tests,
  extract_starting_and_ending_spaces.assertive_tests,
  filter_nodes_by_attributes.assertive_tests,
  find_replace.assertive_tests,
  find_replace_in_descendants_of.assertive_tests,
  fix_ti2_local_links.assertive_tests,
  fold_tag_contents_into_text.assertive_tests,
  fold_tags_into_text.assertive_tests,
  free_children.assertive_tests,
  generate_lbp_breadcrumbs.assertive_tests,
  generate_lbp_prev_next_attributes.assertive_tests,
  generate_lbp_sections_breadcrumbs.assertive_tests,
  generate_lbp_table_of_contents.assertive_tests,
  generate_ti2_table_of_contents.assertive_tests,
  generate_ti2_table_of_contents_html.assertive_tests,
  generate_ti3_index_element.assertive_tests,
  generate_ti3_menu.assertive_tests,
  group_consecutive_children_avoiding.assertive_tests,
  handles_generate_dictionary.assertive_tests,
  handles_generate_ids.assertive_tests,
  handles_substitute.assertive_tests,
  identity.assertive_tests,
  insert_bookend_tags.assertive_tests,
  insert_bookend_text.assertive_tests,
  insert_bookend_text_if_no_attributes.assertive_tests,
  insert_ti2_counter_commands.assertive_tests,
  keep_only_subtrees_and_ancestors_of_nodes_matching_a_key_value_pair.assertive_tests,
  merge_parent_attributes_into_child.assertive_tests,
  normalize_math_delimiters_inside.assertive_tests,
  pair_bookends.assertive_tests,
  pair_double_dollars_together.assertive_tests,
  prepend_append_to_text_children_of.assertive_tests,
  prepend_text.assertive_tests,
  prepend_text_if_has_ancestor_else.assertive_tests,
  rearrange_links.assertive_tests,
  reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node.assertive_tests,
  reinsert_math_dollar.assertive_tests,
  remove_attributes.assertive_tests,
  remove_attributes_for_parents.assertive_tests,
  remove_chapter_number_from_title.assertive_tests,
  remove_empty_lines.assertive_tests,
  remove_empty_tags.assertive_tests,
  remove_outside_subtrees.assertive_tests,
  remove_starting_and_ending_empty_lines.assertive_tests,
  remove_starting_and_ending_spaces.assertive_tests,
  remove_tag.assertive_tests,
  remove_text_nodes_with_singleton_empty_line.assertive_tests,
  rename.assertive_tests,
  rename_attributes.assertive_tests,
  rename_attributes_by_function.assertive_tests,
  rename_when_child_of.assertive_tests,
  rename_with_attributes.assertive_tests,
  replace_in_attribute_values.assertive_tests,
  replace_multiple_spaces_by_one.assertive_tests,
  replace_text_parent_by_text_bookends.assertive_tests,
  split_by_indexed_regexes.assertive_tests,
  split_content_by_low_level_delimiters.assertive_tests,
  split_with_replacement_instructions.assertive_tests,
  surround_elements_by.assertive_tests,
  ti2_carousel_component.assertive_tests,
  trim_spaces_around_newlines.assertive_tests,
  unwrap.assertive_tests,
  unwrap_tag_when_child_of_tag.assertive_tests,
  unwrap_tag_when_parent_of_tag.assertive_tests,
  unwrap_tags_if_attributes_match.assertive_tests,
  unwrap_tags_if_no_attributes.assertive_tests,
  unwrap_tags_when_no_child_meets_condition.assertive_tests,
  unwrap_tags_with_no_text_child.assertive_tests,
  unwrap_tags_with_no_text_descendant.assertive_tests,
  unwrap_when_child_of.assertive_tests,
  unwrap_when_descendant_of.assertive_tests,
  unwrap_when_zero_or_one_children.assertive_tests,
  wrap_adjacent_non_whitespace_text_with.assertive_tests,
  wrap_children_before_in.assertive_tests,
  wrap_element_children.assertive_tests,
]
